### ISSUE TITLE
Skip the "categories" index page

### ISSUE THREAD

**Issue by phae** [chimecms/chime#299]
When clicking through from the main activity page, skip the "categories" index and jump straight to the full list of categories. i.e. Skip just "/edit" and go straight to /edit/categories/

**Comment by tmaybe** [comment]
An alternative would be to not have the categories/ directory at all...

**Comment by phae** [comment]
Yeah, would be down with that. Means someone couldn't accidentally strip off the extra bit of the URL and end up somewhere useless. :)

**Comment by tmaybe** [comment]
@norrishung has a rationale for the categories/ directory that maybe we could discuss in person?

**Comment by norrishung** [comment]
The reason I have all of the articles in its own folder instead of at the top level in Chime Starter is because I am anticipating additional types of pages in the future (e.g., department pages, news/press release articles, project pages etc) and I wanted to keep those things separate. Technically, the categories folder should be named "Articles".

We could put all the articles in the root level now but I feel that it would be messy to try and redo the jekyll site structure once we have to implement these other types of pages.

I'm all for skipping the categories/articles directory in the Chime UI but I realize that's just a temporary fix and might not be worth the effort if we are going to start implementing these other types of pages soon.

But yeah, maybe we can talk about this in person.

**Comment by wpietri** [comment]
This is a really interesting example of the intersection between our technical architecture and the structure of their content repository, so I think it's definitely worth talking about. Also glad to make the temporary fix; sounds like it should be easy enough to do (and undo later).

**Comment by phae** [comment]
Front planning: If there is only 1 folder, automatically redirect to that folder.
