### ISSUE TITLE
the "Sign out" button on the not-allowed page doesn't do anything

### ISSUE THREAD

**Issue by tmaybe** [chimecms/chime#406]
There's a "Sign out" button on the page that loads when you're not authorized to sign in to a site (`/not-allowed`). It's linked to an empty anchor. What should it do, exactly?

**Comment by norrishung** [comment]
I would imagine it would allow the user to sign out of Persona?

We had this problem come up with one of the onboardings but once someone signed into Persona, and they hit the not authorized screen, there was no way for them to switch to a different Persona account so they had to use a different browser.

**Comment by phae** [comment]
+1 - It should be to sign out of a persona account that's already logged in (and not allowed).

**Comment by tmaybe** [comment]
Is there another way to do this at the moment? Can you go to login.persona.org and log-out there?

**Comment by norrishung** [comment]
Users can definitely do that but there's no way they'd know to do that from the Chime app right now. Not sure whats possible, but I see three potential paths:

1. The button simply redirects you to login.persona.org and tells you you should log out of Persona in order to log in as a different user.
2. The button actually triggers a persona signout
3. The button somehow disassociates the current Persona user from the current Chime user and effectively logs them out of Chime. (And gives them the option to sign in again as a different Persona user.)

**Comment by migurski** [comment]
:hand: for option 2. There’s no concept of a current Chime user distinct from a current Persona user—they’re both the person’s email address.

**Comment by tmaybe** [comment]
I'll look into this, there's probably a way to do option 2 (maybe already written but not hooked up!)

**Comment by norrishung** [comment]
This looks like it could be it?

https://developer.mozilla.org/en-US/docs/Web/API/IdentityManager/logout

**Comment by tmaybe** [comment]
probably related, from @wpietri in Slack:


> By the way, it looks like our small red "sign out" button doesn't work if you happen to sign in to an account without access. The big blue one in the upper right corner does, though.
